// <auto-generated />
using CarOrder.Aggregate.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarOrder.Aggregate.Migrations.Order
{
    [DbContext(typeof(OrderContext))]
    [Migration("20190813163550_CarOrder.Aggregate.Model.Context.OrderContext")]
    partial class CarOrderAggregateModelContextOrderContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarOrder.Aggregate.Model.Models.Order", b =>
                {
                    b.Property<long>("Orderitem");

                    b.Property<string>("Engine");

                    b.Property<string>("Make");

                    b.Property<int>("Orderid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Orderitemmodel");

                    b.Property<string>("Year");

                    b.HasKey("Orderitem");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Orderitem = 152223333L,
                            Engine = "Petrol",
                            Make = "AA",
                            Orderid = 0,
                            Orderitemmodel = "Desire - Zxi",
                            Year = "Jan- 2019"
                        },
                        new
                        {
                            Orderitem = 1522233855L,
                            Engine = "Diesel",
                            Make = "MA",
                            Orderid = 0,
                            Orderitemmodel = "Desire - Zxi+",
                            Year = "Jan- 2018"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
